# permissions for end users to view databaseconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: databaseconnection-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: commons-operator
    app.kubernetes.io/part-of: commons-operator
    app.kubernetes.io/managed-by: kustomize
  name: databaseconnection-viewer-role
rules:
- apiGroups:
  - database.zncdata.dev
  resources:
  - databaseconnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.zncdata.dev
  resources:
  - databaseconnections/status
  verbs:
  - get
