# permissions for end users to edit databases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: database-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: commons-operator
    app.kubernetes.io/part-of: commons-operator
    app.kubernetes.io/managed-by: kustomize
  name: database-editor-role
rules:
- apiGroups:
  - stack.zncdata.net
  resources:
  - databases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stack.zncdata.net
  resources:
  - databases/status
  verbs:
  - get
