---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups:
      - zncdata.dev
    resources:
      - databaseconnections
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - zncdata.dev
    resources:
      - databaseconnections/finalizers
    verbs:
      - update
  - apiGroups:
      - zncdata.dev
    resources:
      - databaseconnections/status
    verbs:
      - get
      - patch
      - update

  - apiGroups:
      - zncdata.dev
    resources:
      - databases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - zncdata.dev
    resources:
      - databases/finalizers
    verbs:
      - update
  - apiGroups:
      - zncdata.dev
    resources:
      - databases/status
    verbs:
      - get
      - patch
      - update

  - apiGroups:
      - zncdata.dev
    resources:
      - s3connections
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - zncdata.dev
    resources:
      - s3connections/finalizers
    verbs:
      - update
  - apiGroups:
      - zncdata.dev
    resources:
      - s3connections/status
    verbs:
      - get
      - patch
      - update

  - apiGroups:
      - zncdata.dev
    resources:
      - s3buckets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - zncdata.dev
    resources:
      - s3buckets/finalizers
    verbs:
      - update
  - apiGroups:
      - zncdata.dev
    resources:
      - s3buckets/status
    verbs:
      - get
      - patch
      - update
