apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: commons-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: DatabaseConnection is the Schema for the databaseconnections API
      displayName: Database Connection
      kind: DatabaseConnection
      name: databaseconnections.zncdata.dev
      version: v1alpha1
  description: zncdatadev commons operator
  displayName: commons operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - commons operator zncdatadev
  links:
  - name: Commons Operator
    url: https://github.com/zncdatadev/operator-go
  maintainers:
  - email: huagang517@126.com
    name: wanghuagang
  maturity: alpha
  provider:
    name: zncdatadev
    url: https://github.com/zncdatadev/commons-operator
  version: 0.0.0
