apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: commons-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: DatabaseConnection is the Schema for the databaseconnections API
      displayName: Database Connection
      kind: DatabaseConnection
      name: databaseconnections.stack.zncdata.net
      version: v1alpha1
  description: zncdata-labs commons operator
  displayName: commons operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - commons operator zncdata-labs
  links:
  - name: Commons Operator
    url: https://github.com/zncdata-labs/operator-go
  maintainers:
  - email: huagang517@126.com
    name: wanghuagang
  maturity: alpha
  provider:
    name: zncdata-labs
    url: https://github.com/zncdata-labs/commons-operator
  version: 0.0.0
