apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: commons-catalog
  namespace: kubedatastack-operator
spec:
  sourceType: grpc
  image: quay.io/zncdatadev/commons-operator-catalog:latest
  displayName: commons catalog
  publisher: zncdatadev
  updateStrategy:
    registryPoll:
      interval: 5m
