apiVersion: stack.zncdata.net/v1alpha1
kind: Database
metadata:
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/instance: database-sample
    app.kubernetes.io/part-of: commons-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: commons-operator
  name: database-sample
spec:
  databaseName: znc_prod
  reference: databaseconnection-sample
  credential:
    existingSecret: database-sample-pg-user-1
