apiVersion: zncdata.dev/v1alpha1
kind: DatabaseConnection
metadata:
  labels:
    app.kubernetes.io/name: databaseconnection
    app.kubernetes.io/instance: databaseconnection-sample
    app.kubernetes.io/part-of: commons-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: commons-operator
  name: databaseconnection-sample
spec:
  provider:
    postgres:
      driver: org.postgresql.Driver
      host: postgresql
      port: 5432
      ssl: false
      credential:
        existingSecret: databaseconnect-sample-pg-root-1

