apiVersion: zncdata.dev/v1alpha1
kind: S3Bucket
metadata:
  labels:
    app.kubernetes.io/name: s3bucket
    app.kubernetes.io/instance: s3bucket-sample
    app.kubernetes.io/part-of: commons-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: commons-operator
  name: s3bucket-sample
spec:
  bucketName: znc-warehouse
  reference: s3connection-sample
  credential:
    existSecret: s3bucket-sample-user-1
